[bell]
animation = "EaseOutExpo"
duration = 0

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

# For some reason, this breaks the terminal on macOS since it cannot find a lot of dependencies
# [terminal.shell]
# program = "/bin/zsh"

[window]
decorations = "full"
dynamic_title = true
option_as_alt = "Both"
#startup_mode = "Maximized"

[window.dimensions]
columns = 160
lines = 80

[window.padding]
x = 4
y = 4

[general]

live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/vscode.toml",
    "~/.config/alacritty/keybindings.toml",
]

[terminal]
