[keyboard]
bindings = [
    { key = "Left", mods = "Command", chars = "\u001BB" },
    { key = "Right", mods = "Command", chars = "\u001BF" },
    { key = "Back", mods = "Command", chars = "\u0015" },
]
