[keyboard]

# Move the cursor to the previous word
[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Option"

# Move the cursor to the next word
[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Option"

# Delete the full line
[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Option"

# Delete the previous word
[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

# Move the cursor to the end of the line
[[keyboard.bindings]]
chars = "\u0005"
key = "Right"
mods = "Command"

# Move the cursor to the beginning of the line
[[keyboard.bindings]]
chars = "\u0001"
key = "Left"
mods = "Command"
